import { Project, Task, User, Company, Department, FormTemplate } from '@/types';

export const currentCompany: Company = {
  id: 'c1',
  name: '未来科技有限公司',
  logo: 'https://api.dicebear.com/7.x/shapes/svg?seed=FutureTech',
};

export const departments: Department[] = [
  { id: 'd1', name: '技术部', managerId: 'u2' },
  { id: 'd2', name: '市场部', managerId: 'u3' },
];

export const users: User[] = [
  {
    id: 'u1',
    name: '李总 (Admin)',
    username: 'administrator',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    companyId: 'c1',
    password: 'admin',
  },
  {
    id: 'u2',
    name: '张主管 (技术部经理)',
    username: 'techmanager',
    role: 'manager',
    departmentId: 'd1',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=TechLead',
    companyId: 'c1',
    password: 'admin',
  },
  {
    id: 'u3',
    name: '王主管 (市场部经理)',
    username: 'marketmanager',
    role: 'manager',
    departmentId: 'd2',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=MarketLead',
    companyId: 'c1',
    password: 'admin',
  },
  {
    id: 'u4',
    name: '小赵 (技术员)',
    username: 'developer',
    role: 'employee',
    departmentId: 'd1',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Dev1',
    companyId: 'c1',
    password: 'admin',
  },
  {
    id: 'u5',
    name: '小钱 (市场专员)',
    username: 'marketer',
    role: 'employee',
    departmentId: 'd2',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mkt1',
    companyId: 'c1',
    password: 'admin',
  },
];

export const initialProjects: Project[] = [
  {
    id: '1',
    name: '368减薄款项目',
    description: '368减薄款项目描述',
    progress: 0,
    type: 'department',
    departmentId: 'd1',
    memberIds: ['u1'],
    initiator: '技术部',
    problem: '需减薄设计',
    goal: '减薄10%',
    actions: '优化结构',
    resources: '技术部全员',
    cycle: '2024-Q2',
    benefit: '成本降低5%',
    approval: '李总',
    createdAt: '2024-04-01',
    companyId: 'c1',
    creatorId: 'u1',
  },
  {
    id: '2',
    name: '高光效光源改善方案',
    description: '高光效光源改善方案描述',
    progress: 0,
    type: 'department',
    departmentId: 'd1',
    memberIds: ['u2'],
    initiator: '技术部',
    problem: '光源效率低',
    goal: '效率提升20%',
    actions: '更换光源',
    resources: '技术部全员',
    cycle: '2024-Q2',
    benefit: '能耗降低15%',
    approval: '李总',
    createdAt: '2024-04-02',
    companyId: 'c1',
    creatorId: 'u2',
  },
  {
    id: '3',
    name: 'M9感应器迭代降本项目',
    description: 'M9感应器迭代降本项目描述',
    progress: 0,
    type: 'department',
    departmentId: 'd2',
    memberIds: ['u3'],
    initiator: '市场部',
    problem: '感应器成本高',
    goal: '成本降低10%',
    actions: '迭代设计',
    resources: '预算50万',
    cycle: '2024-Q2',
    benefit: 'ROI 1:3',
    approval: '李总',
    createdAt: '2024-04-03',
    companyId: 'c1',
    creatorId: 'u3',
  },
];

export const initialTasks: Task[] = [
  { id: '1', projectId: '2', title: '架构设计', completed: true, assignee: 'u2' },
  { id: '2', projectId: '2', title: 'API开发', completed: false, assignee: 'u4' },
];

export const formTemplates: FormTemplate[] = [
  {
    id: "ft1",
    name: "手持电钻降本项目",
    code: "PROD-2024-004",
    version: "BOM V2.2",
    companyId: "c1",
    createdAt: "2024-01-05",
  },
  {
    id: "ft2",
    name: "智能音箱降本项目",
    code: "PROD-2024-002",
    version: "BOM V1.5",
    companyId: "c1",
    createdAt: "2024-01-12",
  },
  {
    id: "ft3",
    name: "工业控制器降本项目",
    code: "PROD-2024-002-2",
    version: "BOM V3.1",
    companyId: "c1",
    createdAt: "2024-01-18",
  },
];
